yuumai-tiritumo-gaming/work-github

config/application.rb, db/migrate/20220417195230_devise_create_customers.rb, db/migrate/20220417195259_devise_create_admins.rb, db/schema.rb
customerとadminのpasswordカラムの名前をencrypted_passwordに変更しました
=> [Fix]migrate

app/controllers/admin/sessions_controller.rb, app/views/admin/shared/_links.html.erb, config/routes.rb
=> Admin log in

app/views/layouts/_header.html.erb, app/views/public/customers/show.html.erb
=> Header footer

app/controllers/public/sessions_controller.rb, app/models/customer.rb, app/views/public/sessions/new.html.erb, db/seeds.rb
退会状態の人がログイン出来ないようにした。退会状態の人をシーズに入れた
=> Sign in rejection

app/views/layouts/_header.html.erb, config/routes.rb
ヘッダー内のマイページリンク先が誤っていたため修正。
クラス名前後の半角スペースの過不足を修正。
=> Fix header

Gemfile, Gemfile.lock, app/controllers/public/cart_items_controller.rb, app/helpers/public/cart_items_helper.rb, app/models/cart_item.rb, app/views/public/cart_items/index.html.erb, config/routes.rb, db/seeds.rb
🍰 確認して欲しいポイント ☕️
Gemfile               
　=> [pry-nav]の追加
　　∟binding.pry中にnextコマンドを使用可能に
　=> bundle installの影響でGemfile.lockが自動的に変更されている
routes.rb
　=> 同一URLに同一のメソッドが送られていたのでURL書き換えで回避する目的
CartItemモデル  
　=> varidation記述修正
　　∟適切なオプションではなかったため
seeds.rb             
　=> seeds.rb全体のインデントを調整✍️
　=> cutomerのステータスをtrueに変更
　　∟下記カート内アイテム確認の為
　=> Genre/Item/CartItemのseedデータ作成
　　∟(反映させるには rails db:migrate:reset -> rails db:seed )
🐕そのほかcart_item関連のファイルは実装途中なのであんまり気にしないでね🐈
=> 共通ファイルを数点修正

app/controllers/public/items_controller.rb, app/controllers/public/registrations_controller.rb, app/views/admin/items/_error.html.erb, app/views/admin/items/edit.html.erb, app/views/admin/items/new.html.erb, app/views/public/items/top.html.erb, config/routes.rb
=> Public items

app/controllers/public/cart_items_controller.rb, app/helpers/public/cart_items_helper.rb, app/views/public/cart_items/_all_cart_items.html.erb, app/views/public/cart_items/index.html.erb, app/views/public/cart_items/update.js.erb
リファクタリングしようとしてたのにAjaxの記述がどんどんボロボロになって動かなくなったりして結局
ほぼページ１面非同期で更新することになりました😭
表面上の挙動　　　　　　　  =>　変更なし
clear/destroy/updateのAjax　=> 　正常に動作
=> Cart items

app/controllers/public/customers_controller.rb, app/models/customer.rb, app/views/public/customers/edit.html.erb
会員情報編集画面作成完了。
Customerモデルにバリデーションを設定しています。
=> [Finish]public-registrations-edit

app/views/admin/items/edit.html.erb, app/views/admin/items/new.html.erb
admin_items の　newとeditのviewにブートストラップのやり方をある程度当てはめた。見た目変えただけです。
=> admin_itemsのform

app/views/layouts/_header.html.erb
ヘッダーに検索窓とサクセスメッセージ表示。
クラス名はwebサイトからそのまま引っ張ってきたので、レイアウト修正の時に変更するかもです。
=> [Add]fix-header

app/controllers/public/addresses_controller.rb, app/views/public/addresses/index.html.erb
=> [Finish]public-address-index

app/controllers/public/addresses_controller.rb, app/models/address.rb, app/views/public/addresses/edit.html.erb, app/views/public/addresses/index.html.erb
=> Public address edit

app/controllers/admin/customers_controller.rb, app/views/admin/customers/show.html.erb
=> [Finish]admin-customer-show

app/controllers/admin/customers_controller.rb, app/views/admin/customers/edit.html.erb, app/views/admin/customers/show.html.erb
=> [Finish]admin-customer-edit

app/controllers/public/sessions_controller.rb, app/models/item.rb, app/views/admin/genres/_genre_index.html.erb, app/views/admin/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/public/cart_items/_all_cart_items.html.erb
レイアウト修正
application.html.erb、フラッシュメッセージの表記修正
=> [fix]admin-session-layout

app/controllers/admin/genres_controller.rb, app/javascript/stylesheets/application.scss, app/models/genre.rb, app/views/admin/genres/_genre_index.html.erb, app/views/admin/genres/create.js.erb, app/views/layouts/application.html.erb, app/views/public/cart_items/_all_cart_items.html.erb, config/locales/ja.yml, config/routes.rb
レイアウト修正
該当ページ、フラッシュメッセージのAjax化に伴う
・application.html.erb
・admin/genre controller
・genre model
の編集
ymlはバリデーションエラーメッセージ用にいじったけどなんか翻訳されなくて悲しかったです。
=> [Finish]fix-admin-genre

app/controllers/public/cart_items_controller.rb, app/controllers/public/orders_controller.rb, app/views/public/cart_items/_all_cart_items.html.erb, app/views/public/cart_items/index.html.erb
orderコントローラーにbefore_action定義（空カート注文問題解決用）
レイアウトは修正したけど未完
=> Fix public cart items

app/controllers/public/addresses_controller.rb, app/views/layouts/application.html.erb, app/views/public/addresses/edit.html.erb, app/views/public/addresses/index.html.erb, app/views/public/customers/confirmation.html.erb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, config/routes.rb
ブランチ名はfix-public-addressですが、customerも一緒に編集しています。
public/address,public/customerのレイアウト完了しました。
=> Fix public address

app/controllers/public/cart_items_controller.rb, app/controllers/public/orders_controller.rb, app/views/public/cart_items/_all_cart_items.html.erb, app/views/public/orders/check.html.erb, app/views/public/orders/index.html.erb, app/views/public/orders/new.html.erb, app/views/public/orders/show.html.erb, config/routes.rb
routes.rbの編集とviewでブラウザパックした時のエラーの解消
=> change-routes

app/controllers/public/cart_items_controller.rb, app/javascript/stylesheets/application.scss, app/views/admin/items/edit.html.erb, app/views/admin/items/new.html.erb, app/views/admin/items/show.html.erb, app/views/admin/orders/show.html.erb, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb, app/views/public/items/top.html.erb
【軽微な修正】
カートにアイテムを追加したときの通知を追加した
セレクトフォームの見た目を変更した
ボタンの中の文字を太くした
=> SelectBoxAndButtonTextThicknessAndCartNotice

app/controllers/public/cart_items_controller.rb, app/controllers/public/orders_controller.rb, app/helpers/public/cart_items_helper.rb, app/javascript/stylesheets/application.scss, app/views/public/cart_items/_all_cart_items.html.erb, app/views/public/orders/check.html.erb, app/views/public/orders/conform.html.erb, app/views/public/orders/index.html.erb, app/views/public/orders/new.html.erb, app/views/public/orders/show.html.erb
=> Fix public order

app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb, app/views/public/addresses/edit.html.erb, app/views/public/addresses/index.html.erb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb
admin/customerレイアウト編集完了。
合わせて担当ページのタイトルの背景色修正。
=> [Finish]fix-admin-customer

app/views/public/orders/check.html.erb, app/views/public/orders/new.html.erb
=> [finish]fix-public-order-table_form

app/controllers/admin/order_items_controller.rb, app/controllers/admin/orders_controller.rb
=> [finish]fix

app/controllers/public/cart_items_controller.rb, app/controllers/public/sessions_controller.rb, app/javascript/packs/application.js, app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb, app/views/public/items/show.html.erb, app/views/public/registrations/new.html.erb, config/locales/devise.ja.yml, config/locales/ja.yml
=> Lastfinallastfix

app/views/admin/customers/show.html.erb, app/views/layouts/_header.html.erb, app/views/public/orders/check.html.erb
=> Fix public customer address header
